- name: Variables
  hosts: localhost
  vars:
    course: "DevOps"
    duration: "120hrs"
    fees: "24490/-"
  tasks:
    - name: printing course
      ansible.builtin.debug:
        msg: "Hi Team, we are learning {{course}}, the duration of course is {{duration}}. Amount to be paid is {{fees}}"