- name: Calling Variables from a file
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: display student details
      ansible.builtin.debug:
        msg: "Hi Team, my first name is {{first_name}} middle name is {{middle_name}} last name is {{last_name}}. Date of Birth is {{DOB}}. I'm from {{Village}}"