- name: Passing Variables as arguments
  hosts: localhost
  tasks:
    - name: printing course
      ansible.builtin.debug:
        msg: "Hi Team, we are learning {{course}}, the duration of course is {{duration}}. Amount to be paid is {{fees}}"

###  ansible-playbook 09-vars-args.yml -e course=DevOps -e duration=10hrs -e fees=1000 ###