- name: Checking Variables Preferences
  hosts: localhost
  vars:
    WISHES: "Hi from PLAY Level"
  vars_files:
    - vars.yml
  vars_prompt:
  - name: WISHES
    prompt: Please enter wishes
    private: false
  tasks:
    - name: printing preferences
      # vars:
      #   WISHES: "HI from TASK Level"
      ansible.builtin.debug:
        msg: "{{WISHES}}"

#1. Arguments
#ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 10-vars-preferences.yml -e WISHES="HI-From-ARGS"

#2. TASK Level
#ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 10-vars-preferences.yml
#Please enter wishes: HI from Promt

#3.