- name: Checking Variables Preferences
  hosts: localhost
  vars:
    WISHES: "Hi from PLAY Level"
  vars_files:
    - vars.yml
  vars_prompt:
  - name: WISHES
    prompt: Please enter wishes
    private: false
  tasks:
    - name: printing preferences
      vars:
        WISHES: "HI from TASK Level"
      ansible.builtin.debug:
        msg: "{{WISHES}}"