- name: Giving Default Variable Value using filters
  hosts: localhost
  tasks:
    - name: Course
      ansible.builtin.debug:
        msg: "Hi Welcome to {{course | default('Ansible') }}"

# In this case if the variable course is not defined by the user, by default it will take 'Ansible'
# If we provide the course as argument then it will take priority, example:
# ansible-playbook 14-filters.yml -e course=DevOps
# above play will print "msg": "Hi Welcome to DevOps"

- name: convert to uppercase
  hosts: localhost
  vars:
    name: "Thuttagunta Ganesh Surya Mani Mohan"
  tasks:
    - name: changing to uppercase
      ansible.builtin.debug:
        msg: "{{ name | upper }}"

- name: convert to lowercase
  hosts: localhost
  vars:
    name: "Thuttagunta Ganesh Surya Mani Mohan"
  tasks:
    - name: changing to lowercase
      ansible.builtin.debug:
        msg: "{{ name | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 4, 5, 5, 6, 7, 7, 7, 9]
  tasks:
    - name: removing duplicate numbers from above list
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

- name: print max and min
  hosts: localhost
  vars:
    age: [25,28,29,40,55,60,18,21]
  tasks:
    - name: print max and min age from above list
      ansible.builtin.debug:
        msg: "maximum age: {{ age | max }}, minimum age: {{ age | min }}"

- name: convert dictionary/map to items
  hosts: localhost
  vars:
    dictionary:
      course: AWS+DevOps
      duration: 120hrs
      fees: 24490
  tasks:
    - name: printing dictionary before converting
      ansible.builtin.debug:
        msg: "{{ dictionary }}"

    - name: printing dictionary after converting
      ansible.builtin.debug:
        msg: "{{ dictionary | dict2items }}"

- name: convert items to dictionary
  hosts: localhost
  vars:
    list:
     - {"key": "course", "value": "AWS+DevOps"}
     - {"key": "duration", "value": "120hrs"}
     - {"key": "fees", "value": 24490}
  tasks:
    - name: printing list before converting
      ansible.builtin.debug:
        msg: "{{ list }}"

    - name: printing list after converting
      ansible.builtin.debug:
        msg: "{{ list | items2dict }}"