- name: loop example
  hosts: localhost
  tasks:
    - name: looping names
      ansible.builtin.debug:
        msg: "Hi We're learning {{item}}"
      loop:
        - Linux
        - Shell Scripting
        - Ansible
        - Terraform