- name: loop example
  hosts: localhost
  tasks:
    - name: looping names
      ansible.builtin.debug:
        msg: "Hi We're learning {{item}}"
      loop:
        - Linux
        - Shell Scripting
        - Ansible
        - Terraform

- name: Installing packages via loop
  hosts: node1
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
      loop:
        - mysql
        - nginx